---
token: "secret" # your Discord secret Token
discord:
  channels:
    kc: "id_channel_for_kc_alerts"
    kc_id: "channel used for logging + future result"
    netfamily: "id_channel_for_film_notif"
    error: "id_channel_where_to_send_error_messages"
  roles:
    admin: "id_role_not_used"
    ctv: "id_role_not_used"
    kc: "id_role_not_used"
    netfamily: "id_role_not_used"
log:
  log_message_format: "[{asctime}] [{levelname:<8}] {name}: {message}"
  datetime_format: "%Y-%m-%d %H:%M:%S"
  backup_count: 5
  filename: "/app/log/discord.log"
local: "fr_FR.UTF-8" # for embed messages to be like so Lundi 20 mai
timezone: "Europe/Paris"
kc_api_url: "https://api2.kametotv.fr/karmine" # j'ai trouvé la source, merci a vous :) 
